behaviors:
    CarAgent:
        trainer_type: ppo
        hyperparameters :
            batch_size: 1024
            buffer_size : 1024
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.99
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
            gail:
                strength: 10
                demo_path: Demos/CarAgentDemo.demo
        behavioral_cloning:
                strength: 10
                demo_path: Demos/CarAgentDemo.demo
        max_steps: 10000000
        time_horizon: 64
        summary_freq : 5000