behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10000
      learning_rate: 0.0003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      gamma: 0.99
      max_steps: 500000
      summary_freq: 1000